### ISSUE TITLE
`febs` no longer recognizes `devServer` config options

### ISSUE THREAD

**Issue by zcrumbo** [rei/febs#104]
Since the update to use `MultiCompiler`, the `runDevServer` option no longer parses out dev server options from the compiled instance.
Line 22 of `dev-server.js` has
```js
  const devServerOverrides = compiler.options ? compiler.options.devServer : null;
```
when the parameter `compiler` is now a `MultiCompiler` instance.
So for the same config that existed before that was accessed through `compiler.options.devServer` is now only available through `compiler.compiler[0].options.devServer`

**Comment by peripateticus** [comment]
This will be resolved in #103
