### ISSUE TITLE
npm init should prompt for script configuration

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#22]
If your manually configuring the scripts, it should be documented what the following targets should be set to:

    "scripts" : {
          build: "febs prod"
          test: "mocha" (eventually `febs test`)
https://github.com/rei/febs/issues/new
    }

`febs init` should ask you if you want to add/update the targets.

**Comment by peripateticus** [comment]
Sounds good. We could add an example client `package.json` in the README with a typical setup.

**Comment by peripateticus** [comment]
`init` removed in 3.0.0.
