### ISSUE TITLE
global install api should be clearly documentation or changed

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#25]
After you running `mkdir ~/example-package && cd ~/example-package && npm install -g @rei/febs && febs init`

any `febs` command should look to see if there is a local version of `febs` in the package.json, if there is it should run the local version of febs instead of the globally installed one (while noting that it is doing so).

The globally installed febs version is only available to run `febs init` for scaffolding and as a basic shortcut basic febs commands `febs dev` instead of `npm run dev`, it also provides a way to pass in flags that may not be defined as build tasks. e.g. `febs dev --no-watch --no-dev-server`.

All this should be documented very well or simplified by removing the need for a global install.

**Comment by peripateticus** [comment]
+1

**Comment by DebugXYZ** [comment]
no longer supporting global installation
