### ISSUE TITLE
febs init should generate a package.json

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#26]
It can just call `npm init` and then add properties to package.json after.

**Comment by DebugXYZ** [comment]
related to #22

**Comment by DebugXYZ** [comment]
I meant for the title to not be perscriptive but the first comment is just me quickly throwing out an idea about how to impliment. `npm init` may work if the `febs` executable were bash but I forget that its not.

Related: If we did end up making the exectuable bash it may help with #23, I definately wouldn't call it a recommendation at this point though

I wonder if we could use this: https://github.com/npm/init-package-json

and then make additional modifications by requiring the package.json file, manipulating the object and writing it back to disk, also not a recommendation but may be worth exploring for the task

**Comment by peripateticus** [comment]
Removed `init` in 3.0.0.
