### ISSUE TITLE
should be able to configure febs specific configurations as well as webpack

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#27]
instead of having to create a webpack overrides file to provide an alternative entry point, There should be a proper API exposed to configure changes.

For example, instead of having to create a webpack.overrides.js, to override the entrypoint you should be able to do something like this in your package.json:

{
...
"febs": {
  "entry": {
     'my-cool-bundle': './src/where-ever/entry.js'
  }
...
}

...
}

**Comment by peripateticus** [comment]
Yes, I'd like to explore that idea of a febs config that is a config that contains febs-specific configurations as well as webpack-specific configurations. Conceptually,

```
{
  febs: {}
  webpack: {}
}
```

**Comment by DebugXYZ** [comment]
#56

**Comment by DebugXYZ** [comment]
Catching this thread up, as we have talked about this quite a bit internally. The idea is that we want to have FEBS configured through JSON and not Javascript. This will allow things other than Javascript to be able to read essential configurations around FEBS. Among other things, an asset injector will need the output path and need to be able to grab that independent of language of the asset injector. With the output path being configurable this is now seems essential.

Because Webpack configuration is Javascript we will not be able to merge these two configurations into one file.

**Comment by DebugXYZ** [comment]
This ended up being backwards compatible
