### ISSUE TITLE
`febs test` - FEBS unit test API

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#29]
We would like to be able to execute client unit tests and code coverage through FEBS rather than through external client npm scripts. Several reasons for this:

- ensure unit testing and code coverage available with FEBS
- unit testing tied to the technologies that you're using (Vue, Riot, etc.)
- consistent methodology
- maintainability

So, the goal here is:

- Use the test framework's CLI not API.
- Provide this via FEBS.

Originally, we were doing this via executing mocha CLI commands via a node child process. A problem we were hitting with this is that it is difficult to catch unit test failures via the node child process API. (e.g., https://nodejs.org/api/child_process.html#child_process_child_process). The success and error conditions both stream mocha output through the same callback.

Why CLI? Test frameworks provide all of their functionality via the CLI and often don't even have a documented programmatic API. This also means less code for us to write, test, and maintain.

**Comment by peripateticus** [comment]
As we'd like to focus `febs` on building and not code quality, closing this.
