### ISSUE TITLE
Vue unit test and code coverage capability

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#30]
`febs` needs the ability to run Vue unit tests and code coverage. This is also needed in core `febs`.

**Comment by peripateticus** [comment]
This is very closely tied to #29

**Comment by DebugXYZ** [comment]
yea this is a dupe, my bad!

**Comment by DebugXYZ** [comment]
Re-opening, we have an internal way to temporarily resolve this. But going to keep this open for the long term solution around having vue components be parsed and executed by mocha. 

One solution might be to have an intermediary build step.

**Comment by peripateticus** [comment]
This is available via `vunit`. As `febs` now just focusses on building and not code quality.
