### ISSUE TITLE
Basic validation on`scripts` tasks in package.json

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#39]
There should be some basic validation on the build tasks providing a warning if the recommended tasks aren't being used.

For example, if you run `npm run build` on a package.json and the `build` script is pointing to febs. It would then validate the rest of the tasks as well as the buid task its self.

This will help any accidental miss configurations and in the future provide easier upgrade paths.

It will also make best practice / recommended build scripts clear.

**Comment by peripateticus** [comment]
I'm a little unclear on this one. What would an "accidental misconfiguration" look like? Could you give some examples?

**Comment by DebugXYZ** [comment]
I've encountered some internal customers who had some misconfigurations which prompted me to create this task. Unfortunately I don't remember what the configuration was, maybe it was from an early version?

Example code of how to configure the `scripts` in package.json might also be good for developer usability #16, I know I love to copy-pasta.

It might also be useful for major upgrade paths, for example for #23 we plan on changing the task api. We could warn that the task doesn't match the recommended one.

For example, when we switch the task configuration instructions to say:
`NODE_ENV=prod febs prod`

to:

`febs prod`

I think it would be handy if it had a message like "The FEBS task seems to be misconfigured, you can update it to the recommended task" [link to docs would be a nicity]. If we wanted If we wanted to be really fancy we can show the misconfigured value and the recommended value

It could not actually be a continued point of confusion but we can close and re-open if it ends up being a thing. Seems like it could be excessive? Any thoughts?

**Comment by DebugXYZ** [comment]
Another usecase could be that the user may just add the `build` task and `dev` task but forget to add the rest of the tasks. We may add a new task and the user may not know about the new task.

But again, i think this all could be excessive and if we even decided to do it would be low priority

**Comment by peripateticus** [comment]
Closing for now, let's reopen if misconfiguration of scripts is reported again.
