### ISSUE TITLE
`febs lint`

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#41]
I think a vended linter would be handy

* `febs lint` - would run a linting report outside of webpack
* `febs lint --fix` - would run a linting report and fix what it can automatically

Trick would be to ensure that the linter is configured in the same way as the linter in the build (webpack) to avoid confusion.

**Comment by DebugXYZ** [comment]
I like the later

**Comment by DebugXYZ** [comment]
for a while, if something pops up thats really common we may consider adding it or taking PR's on it at a later point.

**Comment by peripateticus** [comment]
Client code linting feature removed in 3.0.0.
