### ISSUE TITLE
Lint output confusion

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#43]
When the linter runs and has failures, it should be clear that its not failing the build.

**Comment by DebugXYZ** [comment]
Sounds good to me!

**Comment by DebugXYZ** [comment]
I ran into a linter failure today while working on vue ssr stuff (using febs)

Just noting to me self to dig into what happened there. I really thought I had verified that it wasn't failling the build... will report back :)

**Comment by peripateticus** [comment]
Linting is now done separately from `febs`.
