### ISSUE TITLE
Unit tests are failing on .vue file syntax

### ISSUE THREAD

**Issue by JoshCostanza** [rei/febs#46]
Looks like there was a version change of vue-loader that may have caused issues with the VueLoaderPlugin. webpack overrrides don't seem to work either ¯\_(ツ)_/¯..

Getting the following when trying to build with a vue.js file:
`/Users/jcostan/code/content-editor-ui/content-editor-ui/src/main/frontend/node_modules/babel-core/lib/transformation/file/index.js:558
      throw err;
      ^

SyntaxError: /Users/jcostan/code/content-editor-ui/content-editor-ui/src/main/frontend/src/js/components/WelcomePage.vue: Unexpected token (1:0)
> 1 | <script>
    | ^`

**Comment by DebugXYZ** [comment]
thanks for #45  !

**Comment by jcostanza4** [comment]
Tried adding a webpack.overrides.conf.json next to package.json and does not seem to work either.

`/* eslint-disable import/no-extraneous-dependencies */
import { VueLoaderPlugin } from 'vue-loader';

module.exports = {
  module: {
    rules: [
      // ... other rules
      {
        test: /\.vue$/,
        loader: 'vue-loader',
      },
    ],
  },
  plugins: [
    new VueLoaderPlugin(),
  ],
};`

**Comment by jcostanza4** [comment]
reopening as I think this was closed by accident

**Comment by JoshCostanza** [comment]
I noticed one of my packages had vue-loader 14.2.2 and was bumping the version. There is a notable breaking change on the vueLoaderPlugin as part of my findings https://vue-loader.vuejs.org/migrating.html#a-plugin-is-now-required

**Comment by JoshCostanza** [comment]
Working with @peripateticus we found out it is also part of the Unit tests that are failing on .vue file syntax and by doing a build-only run everything builds fine.

**Comment by peripateticus** [comment]
This is really an issue with our internal build and its `test` script. Currently `febs` does not run any unit tests but we will be resolving that in #30.

**Comment by peripateticus** [comment]
Closing as this is a known issue in #30.
