### ISSUE TITLE
Change CSS Scope to Limit to Template

### ISSUE THREAD

**Issue by JoshCostanza** [rei/febs#48]
https://github.com/rei/febs/blob/e85812b8340f065e08841163652c496001d5c761/templates/src/style/entry.less#L1

The example Less file could be scoped to the template rather than the body. The example works but the color change of the body and padding visually break the overall page structure. I would recommend keeping things isolated to the template rather than impact global styles. 

**Proposed:**
App.vue
```
<template>
  <div class="example-vue-component">
    <div id="c1">{{ message }}</div>
  </div>
</template>
```

entry.less
```

.example-vue-component {
  position: relative;
  margin-top: 2px;
  padding: 20px;
  background-color: #000;
  color: white;
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  h1 {
    color: darkcyan
  }

  pre {
    color: chartreuse
  }
}
```

**Comment by peripateticus** [comment]
For this one, in the sample template, that LESS/CSS was really intended to be overwritten when the developer begins development.  Perhaps we should add some comments to `entry.less` to indicate that these should be overridden and are just for the purpose of the startup page?  And/or rename those files to, say, `sample.less`, `sample.template`, etc.

**Comment by peripateticus** [comment]
Here are some screenshots of the current and proposed styling:

Current styling:
![screen shot 2018-09-26 at 11 32 46 am](https://user-images.githubusercontent.com/1110797/46101146-0cd41380-c180-11e8-9f66-73f8cf3f934a.png)


Proposed styling:
![screen shot 2018-09-26 at 11 33 13 am](https://user-images.githubusercontent.com/1110797/46101164-18bfd580-c180-11e8-8b32-1a9b912f60f3.png)

**Comment by JoshCostanza** [comment]
Way better, just change the svg src to `https://satchel.rei.com/media/img/header/rei-co-op-logo-black.svg`

**Comment by peripateticus** [comment]
Right on thanks for that link to the logo! I agree, there really is no need for that extraneous global page style. Lets go with that, I'll swap out that logo too.
