### ISSUE TITLE
make febs init generate a .gitignore file

### ISSUE THREAD

**Issue by JoshCostanza** [rei/febs#51]
FEBS generates the gitignore but **dist** is improperly set as **.dist** instead of **dist/**

**Comment by peripateticus** [comment]
Actually, `febs` does not generate a `.gitignore` file.

**Comment by DebugXYZ** [comment]
Sorry, I may have caused some confusion here. I mentioned to @JoshCostanza that febs init might generate a .gitignore file offhandedly. Is this a feature we would want to add to it?

**Comment by peripateticus** [comment]
I'm for adding this to the documentation and letting the user update their project's `.gitignore` file.  I feel this goes beyond the responsibility of `febs` as this is really related to the client's git repository and `febs` is just a dependency. (See #52).

**Comment by peripateticus** [comment]
`init` removed in 3.0.0.
