### ISSUE TITLE
removing febs init

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#52]
There was some mention that init scaffolding could be confusing / may not be the job of febs. Especially given our internal usage of [ez-up](https://engineering.rei.com/open-source/generating-projects-with-ezup.html). Which I can totally get.

Given that we have #26, #22, #21, and #19, should we just remove it until we have it in a better state? I can definately contribute to the documentation on it if the goal is to reduce confusion before we re-introduce?

**Comment by peripateticus** [comment]
I agree with the `confusing/may not be responsibility of febs` sentiment. I'm hesitant when it comes to `febs` going into parent project and making modifications to client's project files, for example, the `package.json`s, `.gitignore`s, etc. It's getting into the realm of unexpected/atypical behavior that would likely frustrate and/or confuse the user. Additionally, it creates the need for a lot more code/complexity on our part and increased chances of breaking things outside of the realm of `febs`. I like your idea of documentation at this point, at least until we flesh it out more.
