### ISSUE TITLE
FEBS should be able to compile sass

### ISSUE THREAD

**Issue by DebugXYZ** [rei/febs#57]
FEBS should be able to compile sass files. Even though we attempt to use standard css via postcss where we can, for more advanced use cases we use sass (REI Cedar) and febs should be able to compile it.

**Comment by peripateticus** [comment]
`febs` does compile `sass`, see https://github.com/rei/febs/blob/master/test/index-dev-spec.js#L195.

**Comment by DebugXYZ** [comment]
Closing. Thanks!
