### ISSUE TITLE
Upgrade Babel to v7

### ISSUE THREAD

**Issue by peripateticus** [rei/febs#63]
See https://babeljs.io/blog/2018/08/27/7.0.0

This came up recently due to user not being able to use the spread operator by default and required adding the preset and updating their babelrc. We could simply add this to the febs babelrc in the short term. This is included in Babel 7 (https://babeljs.io/blog/2018/08/27/7.0.0#tc39-proposals-https-githubcom-tc39-proposals-support).

Note: It appears that the Riot babel preset for ES2015 syntax we are using is incompatible with Babel 7. You will see the following error around this when compiling:

```
error: Plugin/Preset files are not allowed to export objects, only functions.
```
Removing the Riot preset resolves the issue.  As we know that we no longer intend to support Riot , this may need to wait until the next major when we remove Riot support.

**Comment by DebugXYZ** [comment]
working on an issue with the babelrc location, apparently this is now configurable in babel 7 https://babeljs.io/docs/en/options#config-loading-options
