### ISSUE TITLE
Problems with setting output via febs-config

### ISSUE THREAD

**Issue by lancetharper** [rei/febs#91]
Here is my `febs-config`:
```
{
  "entry": {
    "app": [
      "./docs-src/index.js"
    ]
  },
  "output": {
    "path": "./docs/"
  }
}
```

2 issues I've bumped into:

1. The output path given gets overwritten and buried within additional folders that match the package name -- see here: https://github.com/rei/febs/blob/bb1ba7ca5358da0a33c8447a442b2959cb41d40e/index.js#L76

I want it to output to `docs/` but it ends up in `docs/@rei/icons/`

I tried to get around it by using the `webpack.overrides.conf.js` file but it looks like that gets ignored for setting output path as well. https://github.com/rei/febs/blob/e2d0f308648bc4970ccfedfe7f9c06013b19e56c/index.js#L112-L113

2. You can only provide a path in `febs-config`. The other parts of webpack output, `publicPath` and `filename` are ignored. It looks like this can be changed by providing them in  `webpack.overrides.conf.js` but it's a bit counterintuitive to override parts of output in two places.

**Comment by peripateticus** [comment]
Thanks for submitting issue, @lancetharper! We should be able to get this fixed pretty quickly.

**Comment by dewilli-rei** [comment]
https://github.com/rei/febs/pull/95 now solves this
