### ISSUE TITLE
Vue.js - Single File Components: Configuring a Vue application to support injecting scoped CSS

### ISSUE THREAD

**Issue by kurtlocker** [rei/febs#96]
Hi team,

I'm new to `febs` and would like to know how to properly configure an application to support injecting scoped CSS via SCSS.

I'm creating a new component called `TripOverviewComponent.vue` which looks something like:

```vue
<template>
  <div class="overview">
    Hello, World!
  </div>
</template>

<script>
export default {
  name: 'TripOverviewComponent',
}
</script>

<style lang="scss" scoped>
   @import '../../style/components/trip-overview-component.scss';
</style>
```

After running `NODE_ENV=development febs` and loading my application, I see the hashed attribution on the div but no reference to the actual CSS (inline or in an external file) which theoretically was pre-processed by a series of loaders.

```html
<div data-v-1b10efe2="" class="overview">
  Hello, World!
</div>
```
Any idea on how to get this to work or what I'm doing wrong?

**Comment by peripateticus** [comment]
Resolved offline, not an issue with `febs`.
